"%dev":
  quarkus:
    http:
      port: ${APP_PORT}
    log:
      console:
       enable: true
       format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{4.}] (%t) %s%e%n"
       level: INFO
    sqs:
      endpoint-override: http://localhost:4566
      queue-url: ${QUEUE_URL}
      aws:
        region: ${AWS_DEFAULT_REGION}
        credentials:
          type: static
          static-provider:
            access-key-id: ${AWS_ACCESS_KEY_ID}
            secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    mp:  #propiedades para el listener a la cola SQS
      messaging:
        incoming:
          emission:
            connector: quarkus-amazon-sqs
            queue-url: ${QUEUE_URL}
            wait-time-seconds: 20
    datasource:
      db-kind: ${DB_SOURCE}
      jdbc:
        max-size: ${DB_POOL_MAX}
        min-size: ${DB_POOL_MIN}
        url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_USER_PASSWORD}
    mailer:
      mock: ${EMAIL_MOCK}
      from: ${EMAIL_FROM}
      host: ${EMAIL_HOST}
      port: ${EMAIL_PORT}
      username: ${EMAIL_USER}
      password: ${EMAIL_PASSWORD}
"%lambda":
  quarkus:
    http:
      port: ${APP_PORT}
    lambda:
      handler: org.microservices.notification_emission.infrastructure.input.sqs.SqsHandler
#    datasource:
#       devservices:
#         enabled: false //para que en prod no levante docker
#      jdbc:
#        url: ${ORACLE_JDBC_URL}
#      username: ${ORACLE_USER}
#      password: ${ORACLE_PASS}
