"%dev":
  app:
    sqs:
      queue-url: ${QUEUE_URL}
      consumer:
        poll-interval: ${SQS_POLL_INTERVAL:5s}
        initial-delay: ${SQS_POLL_INITIAL_DELAY:2s}
        max-messages: ${SQS_MAX_MESSAGES:10}
  quarkus:
    http:
      port: ${APP_PORT}
    sqs:
      endpoint-override: http://localhost:4566
      aws:
        region: ${AWS_DEFAULT_REGION}
        credentials:
          type: static
          static-provider:
            access-key-id: ${AWS_ACCESS_KEY_ID}
            secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    datasource:
      db-kind: ${DB_SOURCE}
      jdbc:
        max-size: ${DB_POOL_MAX}
        min-size: ${DB_POOL_MIN}
        url: {DB_URL}
      username: ${DB_USER}
      password: ${DB_PASSWORD}
    mailer:
      mock: ${EMAIL_MOCK}
      from: ${EMAIL_FROM}
      host: ${EMAIL_HOST}
      port: ${EMAIL_PORT}
      username: ${EMAIL_USER}
      password: ${EMAIL_PASSWORD}
"%lambda":
  quarkus:
    http:
      port: ${LAMBDA_HTTP_PORT}

#    datasource:
#       devservices:
#         enabled: false //para que en prod no levante docker
#      jdbc:
#        url: ${ORACLE_JDBC_URL}
#      username: ${ORACLE_USER}
#      password: ${ORACLE_PASS}
